server:
  port: 80
spring:
  application:
    name: crowd-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
zuul:
  ignored-services: "*"
  sensitive-headers: "*"
  routes:
    crowd-portal:
      service-id: crowd-auth
      path: /**